.TH "dsa::linklist< type >" 3 "Wed Jun 15 2016" "Version 1.0.0" "DSA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
dsa::linklist< type > \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <linklist\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBlinklist\fP ()"
.br
.ti -1c
.RI "bool \fBisempty\fP ()"
.br
.ti -1c
.RI "void \fBempty\fP ()"
.br
.ti -1c
.RI "\fBlli\fP \fBsize\fP ()"
.br
.ti -1c
.RI "void \fBoperator=\fP (\fBlinklist\fP< type > from)"
.br
.ti -1c
.RI "type & \fBoperator[]\fP (\fBlli\fP index)"
.br
.ti -1c
.RI "void \fBadd_back\fP (type param)"
.br
.ti -1c
.RI "void \fBadd_front\fP (type param)"
.br
.ti -1c
.RI "void \fBpop_front\fP ()"
.br
.ti -1c
.RI "void \fBpop_back\fP ()"
.br
.ti -1c
.RI "void \fBremove_at\fP (\fBlli\fP index)"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<class type> \fBdsa::linklist\fP< type >::\fBlinklist\fP ()\fC [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "template<class type> void \fBdsa::linklist\fP< type >::add_back (type param)\fC [inline]\fP"

.SS "template<class type> void \fBdsa::linklist\fP< type >::add_front (type param)\fC [inline]\fP"

.SS "template<class type> void \fBdsa::linklist\fP< type >::empty ()\fC [inline]\fP"

.SS "template<class type> bool \fBdsa::linklist\fP< type >::isempty ()\fC [inline]\fP"

.SS "template<class type> void \fBdsa::linklist\fP< type >::operator= (\fBlinklist\fP< type > from)\fC [inline]\fP"

.SS "template<class type> type& \fBdsa::linklist\fP< type >::operator[] (\fBlli\fP index)\fC [inline]\fP"

.SS "template<class type> void \fBdsa::linklist\fP< type >::pop_back ()\fC [inline]\fP"

.SS "template<class type> void \fBdsa::linklist\fP< type >::pop_front ()\fC [inline]\fP"

.SS "template<class type> void \fBdsa::linklist\fP< type >::remove_at (\fBlli\fP index)\fC [inline]\fP"

.SS "template<class type> \fBlli\fP \fBdsa::linklist\fP< type >::size ()\fC [inline]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for DSA from the source code\&.
