.TH "dsa::queue< type >" 3 "Wed Jun 15 2016" "Version 1.0.0" "DSA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
dsa::queue< type > \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <queue\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBqueue\fP ()"
.br
.ti -1c
.RI "type \fBenqueue\fP (type param)"
.br
.ti -1c
.RI "type \fBdequeue\fP ()"
.br
.ti -1c
.RI "type \fBfront_element\fP ()"
.br
.ti -1c
.RI "type \fBrear_element\fP ()"
.br
.ti -1c
.RI "void \fBoperator=\fP (\fBqueue\fP< type > from)"
.br
.ti -1c
.RI "\fBlli\fP \fBsize\fP ()"
.br
.ti -1c
.RI "bool \fBisempty\fP ()"
.br
.ti -1c
.RI "void \fBempty\fP ()"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<class type> \fBdsa::queue\fP< type >::\fBqueue\fP ()\fC [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "template<class type> type \fBdsa::queue\fP< type >::dequeue ()\fC [inline]\fP"

.SS "template<class type> void \fBdsa::queue\fP< type >::empty ()\fC [inline]\fP"

.SS "template<class type> type \fBdsa::queue\fP< type >::enqueue (type param)\fC [inline]\fP"

.SS "template<class type> type \fBdsa::queue\fP< type >::front_element ()\fC [inline]\fP"

.SS "template<class type> bool \fBdsa::queue\fP< type >::isempty ()\fC [inline]\fP"

.SS "template<class type> void \fBdsa::queue\fP< type >::operator= (\fBqueue\fP< type > from)\fC [inline]\fP"

.SS "template<class type> type \fBdsa::queue\fP< type >::rear_element ()\fC [inline]\fP"

.SS "template<class type> \fBlli\fP \fBdsa::queue\fP< type >::size ()\fC [inline]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for DSA from the source code\&.
