.TH "dsa::stack< type >" 3 "Wed Jun 15 2016" "Version 1.0.0" "DSA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
dsa::stack< type > \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <stack\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBstack\fP ()"
.br
.ti -1c
.RI "type \fBpush\fP (type param)"
.br
.ti -1c
.RI "type \fBpop\fP ()"
.br
.ti -1c
.RI "type \fBtop_element\fP ()"
.br
.ti -1c
.RI "\fBlli\fP \fBsize\fP ()"
.br
.ti -1c
.RI "bool \fBisempty\fP ()"
.br
.ti -1c
.RI "void \fBempty\fP ()"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<class type > \fBdsa::stack\fP< type >::\fBstack\fP ()\fC [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "template<class type > void \fBdsa::stack\fP< type >::empty ()\fC [inline]\fP"

.SS "template<class type > bool \fBdsa::stack\fP< type >::isempty ()\fC [inline]\fP"

.SS "template<class type > type \fBdsa::stack\fP< type >::pop ()\fC [inline]\fP"

.SS "template<class type > type \fBdsa::stack\fP< type >::push (type param)\fC [inline]\fP"

.SS "template<class type > \fBlli\fP \fBdsa::stack\fP< type >::size ()\fC [inline]\fP"

.SS "template<class type > type \fBdsa::stack\fP< type >::top_element ()\fC [inline]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for DSA from the source code\&.
