.TH "dsa::snode< type >" 3 "Wed Jun 15 2016" "Version 1.0.0" "DSA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
dsa::snode< type > \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <stack\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBsnode\fP ()"
.br
.ti -1c
.RI "\fBsnode\fP (type param)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBsnode\fP * \fBprev\fP"
.br
.ti -1c
.RI "type \fBdata\fP"
.br
.ti -1c
.RI "\fBsnode\fP * \fBnext\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<class type> \fBdsa::snode\fP< type >::\fBsnode\fP ()\fC [inline]\fP"

.SS "template<class type> \fBdsa::snode\fP< type >::\fBsnode\fP (type param)\fC [inline]\fP"

.SH "Member Data Documentation"
.PP 
.SS "template<class type> type \fBdsa::snode\fP< type >::data"

.SS "template<class type> \fBsnode\fP* \fBdsa::snode\fP< type >::next"

.SS "template<class type> \fBsnode\fP* \fBdsa::snode\fP< type >::prev"


.SH "Author"
.PP 
Generated automatically by Doxygen for DSA from the source code\&.
