.TH "linklist.h" 3 "Wed Jun 15 2016" "Version 1.0.0" "DSA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
linklist.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBdsa::node< type >\fP"
.br
.ti -1c
.RI "class \fBdsa::linklist< type >\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBdsa\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBlli\fP   long long int"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define lli   long long int"

.SH "Author"
.PP 
Generated automatically by Doxygen for DSA from the source code\&.
