.TH "main.cpp" 3 "Wed Jun 15 2016" "Version 1.0.0" "DSA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
main.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include <cstdlib>\fP
.br
\fC#include <iostream>\fP
.br
\fC#include 'linklist\&.h'\fP
.br
\fC#include 'queue\&.h'\fP
.br
\fC#include 'stack\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP (int argc, char **argv)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int main (int argc, char ** argv)"

.SH "Author"
.PP 
Generated automatically by Doxygen for DSA from the source code\&.
